// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import GlobalController from "./global_controller"
application.register("global", GlobalController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MainController from "./main_controller"
application.register("main", MainController)

import PostController from "./post_controller"
application.register("post", PostController)

import ShowController from "./show_controller"
application.register("show", ShowController)

import { registerPolarisControllers } from "polaris-view-components"
registerPolarisControllers(Stimulus)

import PaginationController from "./pagination_controller"
application.register("pagination", PaginationController)
